export enum Role {
  ADMIN = 'ADMIN',
  SECURITY_GUARD = 'SECURITY_GUARD',
  PROPERTY_OWNER = 'PROPERTY_OWNER',
}

export enum VisitorType {
  ONE_TIME = 'ONE_TIME',
  SCHEDULED = 'SCHEDULED',
  PERMANENT = 'PERMANENT',
}

export enum EntryMethod {
  QR_CODE = 'QR_CODE',
  NATIONAL_ID = 'NATIONAL_ID',
  NAME = 'NAME',
  VEHICLE_PLATE = 'VEHICLE_PLATE',
  MANUAL = 'MANUAL',
}

export enum IncidentType {
  SUSPICIOUS_ACTIVITY = 'SUSPICIOUS_ACTIVITY',
  VEHICLE_DAMAGE = 'VEHICLE_DAMAGE',
  LOST_ITEMS = 'LOST_ITEMS',
  EMERGENCY = 'EMERGENCY',
  OTHER = 'OTHER',
}

export enum PropertyStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  UNDER_MAINTENANCE = 'UNDER_MAINTENANCE',
}

export enum PersonType {
  VISITOR = 'VISITOR',
  EMPLOYEE = 'EMPLOYEE',
  CONTRACTOR = 'CONTRACTOR',
  FAMILY_MEMBER = 'FAMILY_MEMBER',
  RESIDENT = 'RESIDENT',
}

export enum NotificationType {
  VISITOR_ARRIVAL = 'VISITOR_ARRIVAL',
  VISITOR_DEPARTURE = 'VISITOR_DEPARTURE',
  EMPLOYEE_ARRIVAL = 'EMPLOYEE_ARRIVAL',
  EMPLOYEE_DEPARTURE = 'EMPLOYEE_DEPARTURE',
  AUTHORIZATION_REQUEST = 'AUTHORIZATION_REQUEST',
  AUTHORIZATION_APPROVED = 'AUTHORIZATION_APPROVED',
  AUTHORIZATION_CANCELLED = 'AUTHORIZATION_CANCELLED',
  INCIDENT_REPORTED = 'INCIDENT_REPORTED',
  SYSTEM_ALERT = 'SYSTEM_ALERT',
}
